<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="css.css"?>
<!DOCTYPE store [
    <!ELEMENT store (product+)>
    <!ELEMENT product (name, category,price)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT category (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ENTITY Byn "BYN" >
]>
<store>
    <product>
        <name>Смартфон  </name>
        <category>Электроника</category>
        <price>799,00 &Byn;</price>
    </product>
    <product>
        <name>Ноутбук</name>
        <category>Компьютеры</category>
        <price>3627,00 &Byn;</price>
    </product>
    <product>
        <name>Холодильник</name>
        <category>Бытовая техника</category>
        <price>2699,00 &Byn;</price>
    </product>
    <product>
        <name>Телевизор</name>
        <category>Электроника</category>
        <price>2140,00 &Byn;</price>
    </product>
    <product>
        <name>Микроволновка</name>
        <category>Бытовая техника</category>
        <price>399,00 &Byn;</price>
    </product>
</store>